backend:
  name: git-gateway
  branch: master
  squash_merges: true

#publish_mode: editorial_workflow

media_library:
  name: cloudinary
  #output_filename_only: true
  config:
    #default_transformations:
    #  -   - fetch_format: auto
    #        width: 160
    #        quality: auto
    #        crop: scale
    cloud_name: ruapehu-college
    api_key: 389673978476183
    
collections:
  - name: "slider_images"
    label: "Slider Images"
    label_singular: "Slider Image"
    folder: "source/_slider_images"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", default: "Title"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "text", required: false}

  - name: "newsletters"
    label: "Newsletters"
    label_singular: "Newsletter"
    folder: "source/_newsletters"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", default: "Title"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Filename", name: "file", widget: "file"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}

  - name: "events"
    label: "Events"
    label_singular: "Event"
    folder: "source/_events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
    - {label: "Title", name: "title", widget: "string", default: "Title"}
    - {label: "Date", name: "date", widget: "date"}
    - {label: "Image Filename", name: "image", widget: "image", required: false}
    - {label: "Short Intro", name: "short", widget: "text", default: "One paragraph article intro"}
    - {label: "Body", name: "body", widget: "markdown"}
    - {label: "Tags", name: "tags", widget: "list", required: false}

  - name: "our_School"
    label: "Our School Pages"
    label_singular: Our School Page
    folder: "source/_our_school"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
    - {label: "Title", name: "title", widget: "string", default: "Title"}
    - {label: "Date", name: "date", widget: "date"}
    - {label: "Image Filename", name: "image", widget: "image", required: false}
    - {label: "Body", name: "body", widget: "markdown"}
    - {label: "Tags", name: "tags", widget: "list", required: false}

  - name: "curriculum"
    label: "Curriculum Pages"
    label_singular: Curriculum Page
    folder: "source/_curriculum"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
    - {label: "Title", name: "title", widget: "string", default: "Title"}
    - {label: "Date", name: "date", widget: "date"}
    - {label: "Image Filename", name: "image", widget: "image", required: false}
    - {label: "Body", name: "body", widget: "markdown"}
    - {label: "Tags", name: "tags", widget: "list", required: false}

  - name: "enrolment"
    label: "Enrolment Pages"
    label_singular: Enrolment Page
    folder: "source/_enrolment"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
    - {label: "Title", name: "title", widget: "string", default: "Title"}
    - {label: "Date", name: "date", widget: "date"}
    - {label: "Image Filename", name: "image", widget: "image", required: false}
    - {label: "Body", name: "body", widget: "markdown"}
    - {label: "Tags", name: "tags", widget: "list", required: false}

  - name: "international"
    label: "International Pages"
    label_singular: International Page
    folder: "source/_international"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
    - {label: "Title", name: "title", widget: "string", default: "Title"}
    - {label: "Date", name: "date", widget: "date"}
    - {label: "Image Filename", name: "image", widget: "image", required: false}
    - {label: "Body", name: "body", widget: "markdown"}
    - {label: "Tags", name: "tags", widget: "list", required: false}

  - name: "subjects"
    label: "Subjects"
    label_singular: Subject
    folder: "source/_subjects"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
    - {label: "Title", name: "title", widget: "string", default: "Title"}

  - name: "courses"
    label: "Courses"
    label_singular: Course
    folder: "source/_courses"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
    - {label: "Title", name: "title", widget: "string", default: "Title"}
    - {label: "Year", name: "year", widget: "number"}
    - {label: "Course Level", name: "level", widget: "select", options: ['Year 9', 'Year 10','NCEA 1','NCEA 2','NCEA 3','NCEA 1 and 2', 'NCEA 2 and 3', 'NCEA 1,2 and 3']}
    - {label: "Assessment Type", name: "assessment", widget: "select", options: ['Achievement Standard', 'Unit Standard','Achievement Standard and Unit Standard']}
    - {label: "Fees", name: "fees", widget: "string", default: "N/A"}
    - label: "Subject"
      name: "subject"
      widget: "relation"
      collection: "subjects"
      searchFields: ["title"]
      valueField: "title"
      displayFields: ["title"]

  - name: "assessments"
    label: "Assessments"
    label_singular: Assessment
    folder: "source/_assessments"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
    - {label: "Title", name: "title", widget: "string", default: "Title"}
    - label: "Course"
      name: "course"
      widget: "relation"
      collection: "courses"
      searchFields: ["title"]
      valueField: "title"
      displayFields: ["title"]
    - {label: "Description", name: "description", widget: "text"}
    - {label: "Level", name: level, widget: number, default: "0"}
    - {label: "Credits", name: credits, widget: number, default: "0"}
    - {label: "Assessment", name: assessment, widget: select, options: ["Internal","External"], default: ["External"]}

  - name: "sports"
    label: "Sports"
    label_singular: Sport
    folder: "source/_sports"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
    - {label: "Title", name: "title", widget: "string", default: "Title"}
    - {label: "Image", name: "image", widget: "image", required: false}
    - {label: "Body", name: "body", widget: "text", required: false}
    
  - name: "cultural"
    label: "Cultural"
    label_singular: Cultural
    folder: "source/_cultural"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
    - {label: "Title", name: "title", widget: "string", default: "Title"}
    - {label: "Image", name: "image", widget: "image", required: false}
    - {label: "Body", name: "body", widget: "text", required: false}